# Path to telemac root dir
export HOMETEL=$CONDA_PREFIX/opentelemac

# Backup original environment variables if not already done
if [[ -z "${_TELEMAC_OLD_PATH+x}" ]]; then
    export _TELEMAC_OLD_PATH="${PATH}"
fi
if [[ -z "${_TELEMAC_OLD_PYTHONPATH+x}" ]]; then
    export _TELEMAC_OLD_PYTHONPATH="${PYTHONPATH:-}"
fi

# Configuration file (generated by cmake)
export SYSTELCFG=$HOMETEL/systel.cfg

# Adding TELEMAC bins, python scripts and libs to PATH/PYTHONPATH
export PATH=$HOMETEL/bin:$HOMETEL/scripts/python3:$PATH
export PYTHONPATH=$HOMETEL/scripts/python3:$HOMETEL/lib:$PYTHONPATH

# Shared library path (platform-dependent)
if [[ "$(uname)" == "Darwin" ]]; then
    if [[ -z "${_TELEMAC_OLD_DYLD_LIBRARY_PATH+x}" ]]; then
        export _TELEMAC_OLD_DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
    fi
    export DYLD_LIBRARY_PATH=$HOMETEL/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}
else
    if [[ -z "${_TELEMAC_OLD_LD_LIBRARY_PATH+x}" ]]; then
        export _TELEMAC_OLD_LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"
    fi
    export LD_LIBRARY_PATH=$HOMETEL/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi
